apiVersion: v1
kind: Namespace
metadata:
  name: instabug
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: instabug
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yousabu/instabug-intern-challenge.git
    path: kubernetes
    targetRevision: HEAD
    directory:
      recurse: true
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: instabug
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
